[package]
name = "chains-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = { version = "6.1.0", features = ["rayon"] }
fnv = "1.0.7"
indexmap = { version = "2.7.0", features = ["rayon"] }
rand = "0.8.5"
rayon = "1.10.0"
